### ISSUE TITLE
Error when using rtsp_authgrinder

### ISSUE THREAD

**Issue by CBT135** [tektengu/rtsp_authgrinder#1]
Dear Sir,

When I use the rtsp_authgrinder, I have the following error 
"root@kali:~/RTSP/rtsp_authgrinder-master# python rtsp_authgrind.py -l admin -p password 78.240.244.20:554

```
 rtsp_authgrinder.py - Brute forcing tool for RTSP Protocol
```

   Copyright (C) 2014 Luke Stephens and Tek Security Group, LLC
   This program comes with ABSOLUTELY NO WARRANTY. This is free software, and
   you are welcome to use and redistribute it under certain conditions. See
   the license file provided with the distribution,
   or https://github.com/tektengu/rtsp_authgrinder/license.txt

---

Starting RTSP Auth Grinder on IP: 78.240.244.20 and PORT: 554
Running with 50 threads
There are 1 user names to test
There are 1 passwords to test
Total combinations to test are 1

---

Digest Auth is supported and starting run with Digest Auth...
Traceback (most recent call last):
  File "rtsp_authgrind.py", line 400, in <module>
    test_auth_and_run()
  File "rtsp_authgrind.py", line 342, in test_auth_and_run
    perform_rtsp_auth(user, password, creator)
NameError: global name 'perform_rtsp_auth' is not defined"

Do you please know what is wrong ?
Thanks a lot,
With best regards,
Cedric.

**Comment by tektengu** [comment]
Cedric,

Thanks for being a user of AuthGrinder...

The errors you are getting result from the fact Digest Auth is not currently implemented, and unfortunately I left some code in that was not in service. I pushed a current version that let's you know that it is not properly implemented.

In your case the Basic Auth is not finding your user/password combinations work, but the target you are targeting supports Digest Auth as well - so it tries to do Digest Auth (which as stated is not currently implemented).
